name: Rust

on: [push]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - run: |
        rustc -vV
        cargo -vV
    - name: Build & run tests
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64
        cargo test --release --verbose
      shell: cmd
